{"name": "Проверка ответа при создании заказа запросом с невалидным хэшем ингредиента аутентифицированным юзером", "status": "failed", "statusDetails": {"message": "AssertionError: assert (400 == 500)\n +  where 400 = <Response [400]>.status_code", "trace": "self = <test_create_order.TestCreateOrder object at 0x0000020C8E403110>\ncreate_new_user_and_delete = ({'email': 'morganjoseph@yahoo.com', 'name': 'Всемил', 'password': '&7aN^Jw!uw'}, {'accessToken': 'Bearer eyJhbGciOiJI...a3294bf7629e0bee80c8942b89f817a12701', 'success': True, 'user': {'email': 'morganjoseph@yahoo.com', 'name': 'Всемил'}})\n\n    @allure.title('Проверка ответа при создании заказа запросом с невалидным хэшем ингредиента '\n                  'аутентифицированным юзером')\n    @allure.description('В запрос передается хэш несуществующего ингредиента. Аккаунт для проверки создается фикстурой '\n                        'перед тестом и удаляется после.')\n    def test_create_order_invalid_ingredients_authenticated_user_expected_error(self, create_new_user_and_delete):\n        headers = {'Authorization': create_new_user_and_delete[1]['accessToken']}\n        payload = {'ingredients': [IngredientData.invalid_hash_ingredient]}\n        response = requests.post(Urls.order_create, data=payload, headers=headers)\n>       assert response.status_code == 500 and response.json() == {\"success\": False,\n                                                                   \"message\": \"One or more ids provided are incorrect\"}\nE       assert (400 == 500)\nE        +  where 400 = <Response [400]>.status_code\n\ntests\\test_create_order.py:56: AssertionError"}, "description": "В запрос передается хэш несуществующего ингредиента. Аккаунт для проверки создается фикстурой перед тестом и удаляется после.", "start": 1733159332165, "stop": 1733159332616, "uuid": "e6984c73-1451-4aa6-acbc-3c5955f4bf37", "historyId": "c78dc2f65c70f2d33e631820a2d7f09a", "testCaseId": "c78dc2f65c70f2d33e631820a2d7f09a", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_invalid_ingredients_authenticated_user_expected_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "LAPTOP-KPF2QR88"}, {"name": "thread", "value": "23496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}