{"name": "Проверка ответа на запрос изменения данных неаутентифицированного пользователя", "status": "failed", "statusDetails": {"message": "AssertionError: assert (400 == 401)\n +  where 400 = <Response [400]>.status_code", "trace": "self = <test_user_update_.TestUserUpdate object at 0x0000020C8E448050>\n\n    @allure.title('Проверка ответа на запрос изменения данных неаутентифицированного пользователя')\n    def test_update_user_unauthenticated_expected_error(self):\n        response = requests.patch(Urls.user_update, headers=Urls.headers, data=TestUserUpdate.updated_user_data)\n>       assert response.status_code == 401 and response.json() == {'success': False,\n                                                                   'message': 'You should be authorised'}\nE       assert (400 == 401)\nE        +  where 400 = <Response [400]>.status_code\n\ntests\\test_user_update_.py:24: AssertionError"}, "start": 1733159343736, "stop": 1733159344226, "uuid": "6ea0ddc2-f14e-4e64-aea4-19433ad4ab06", "historyId": "91612902ad9b8abab2258a42ef668142", "testCaseId": "91612902ad9b8abab2258a42ef668142", "fullName": "tests.test_user_update_.TestUserUpdate#test_update_user_unauthenticated_expected_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_update_"}, {"name": "subSuite", "value": "TestUserUpdate"}, {"name": "host", "value": "LAPTOP-KPF2QR88"}, {"name": "thread", "value": "23496-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_update_"}]}